jwt:
  secret:
    key: Zjg4ZDQ0MTE2NjFmZWIyMDQyNDYzOWY1YjY1MmNmMThkNmI3NTE1ZTU3YzAzMWFiZjdlMmJhOGVhN2VlNjc1OGUxNjJlYmVhMjcxZjhmNDYwOGI4N2RlMGFlZDU1OTZhMDEzNjlhOTk0NGFkMjAyODRiZDcwMDAxYzNjNzg5Y2E=
  expire:
    length: 600000